"""empty message

Revision ID: 25207f8a0b15
Revises: 
Create Date: 2023-05-24 01:55:42.425829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25207f8a0b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vtuber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('kanji', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('units', mysql.JSON(), nullable=True),
    sa.Column('debut', sa.Date(), nullable=True),
    sa.Column('fanname', sa.String(length=50), nullable=True),
    sa.Column('zodiac', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('youtube', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fanname'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('kanji'),
    sa.UniqueConstraint('youtube')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vtuber')
    # ### end Alembic commands ###
