"""holoapi_init_db

Revision ID: 7e238e66b44c
Revises: 
Create Date: 2023-05-24 22:22:36.015140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e238e66b44c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vtuber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('kanji', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('units', mysql.JSON(), nullable=True),
    sa.Column('debut', sa.Date(), nullable=True),
    sa.Column('fanname', sa.String(length=50), nullable=True),
    sa.Column('zodiac', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('youtube', sa.String(length=150), nullable=True),
    sa.Column('illust', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fanname'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('kanji'),
    sa.UniqueConstraint('youtube')
    )
    op.create_table('avatares',
    sa.Column('avid', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('creator', sa.String(length=50), nullable=True),
    sa.Column('app', sa.String(length=50), nullable=True),
    sa.Column('vtuber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vtuber_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('avid'),
    sa.UniqueConstraint('file'),
    sa.UniqueConstraint('source')
    )
    op.create_table('hashtags',
    sa.Column('htid', sa.Integer(), nullable=False),
    sa.Column('stream_tag', sa.String(length=70), nullable=True),
    sa.Column('fanart_tag', sa.String(length=70), nullable=True),
    sa.Column('vtuber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vtuber_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('htid'),
    sa.UniqueConstraint('fanart_tag'),
    sa.UniqueConstraint('stream_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtags')
    op.drop_table('avatares')
    op.drop_table('vtuber')
    # ### end Alembic commands ###
