"""empty message

Revision ID: d873f631951c
Revises: 
Create Date: 2023-06-05 12:13:27.970938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd873f631951c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('integrity', sa.String(length=150), nullable=False),
    sa.Column('filebytes', sa.LargeBinary(length=10485760), nullable=False),
    sa.CheckConstraint('LENGTH(filebytes) <= 10485760', name='check_bytes_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('integrity')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vtuber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('kanji', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('units', mysql.JSON(), nullable=True),
    sa.Column('debut', sa.Date(), nullable=True),
    sa.Column('fanname', sa.String(length=50), nullable=True),
    sa.Column('zodiac', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('youtube', sa.String(length=150), nullable=True),
    sa.Column('illust', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fanname'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('kanji'),
    sa.UniqueConstraint('youtube')
    )
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('vt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vt_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avatares',
    sa.Column('avid', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('creator', sa.String(length=50), nullable=True),
    sa.Column('app', sa.String(length=50), nullable=True),
    sa.Column('vtuber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vtuber_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('avid'),
    sa.UniqueConstraint('file'),
    sa.UniqueConstraint('source')
    )
    op.create_table('hashtags',
    sa.Column('htid', sa.Integer(), nullable=False),
    sa.Column('stream_tag', sa.String(length=70), nullable=True),
    sa.Column('fanart_tag', sa.String(length=70), nullable=True),
    sa.Column('vtuber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vtuber_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('htid'),
    sa.UniqueConstraint('fanart_tag'),
    sa.UniqueConstraint('stream_tag')
    )
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socialapp', sa.String(length=50), nullable=True),
    sa.Column('socialurl', sa.String(length=150), nullable=True),
    sa.Column('vtuber_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vtuber_id'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('socialurl')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('album', sa.String(length=50), nullable=True),
    sa.Column('releasedate', sa.Date(), nullable=True),
    sa.Column('compositor', sa.String(length=40), nullable=True),
    sa.Column('lyrics', sa.String(length=40), nullable=True),
    sa.Column('albumpt', sa.String(length=170), nullable=True),
    sa.Column('vtid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vtid'], ['vtuber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('social')
    op.drop_table('hashtags')
    op.drop_table('avatares')
    op.drop_table('aliases')
    op.drop_table('vtuber')
    op.drop_table('user')
    op.drop_table('files')
    # ### end Alembic commands ###
